### ISSUE TITLE
Future Upgrades

### ISSUE THREAD

**Issue by TheScree** [MalekaiProject/malekaiOrg#11]
Sorta Planned for V2.0

- [x] ~~Export current Table view to XLS (or Google Docs maybe?)~~
- [ ] Login required via OAuth (to submit data reports/prevent inevitable spam)
- [x] ~~Official Patch Notes Integration (into our version) and Storage (keep back history of all notes)~~

**Comment by MichaelFedora** [comment]
+ in-web edits?

The "export current Table view to ***CSV***" would depend on how complicated our table component will be. What if instead we just exported our raw JSON data as a CSV (i.e. generated from /crowfall-data repo)?
