### ISSUE TITLE
Remaining Features

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/malekaiOrg#3]
- [x] Move to vue-good-table
- [x] "Splash Image" background needs to stretch whole length of page. 
- [x] Create "changelog" component to be used throughout site.
- [ ] Guild Page
- [ ] Patchnotes Page
- [ ] Crafting Page
- [ ] Skills Page
- [x] Flag modal (to add message and confirm they want to flag the data)
- [x] Update home page to use changelog + search
- [x] New Header
- [x] New Footer

**Comment by TheScree** [comment]
Updated OP to include new items on to-do list.

**Comment by TheScree** [comment]
Broke these out into individual issues for easy-claimability.
